name: wallpaper_app_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+13

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  platform: ^3.1.0

 # This is hhtp network
  http: ^0.13.4

   # This is database
  sqflite: ^2.0.2

   # This is animation bottom bar
  salomon_bottom_bar: ^3.3.0

   # This is network check detected
  data_connection_checker: ^0.3.4

   # This is link webview oritation
  url_launcher: ^6.0.17

   # This is custom toast
  fluttertoast: ^8.0.7

  # This is lisview click animation
  animations: ^2.0.2

  # This is backround colors animation
  simple_animations: ^4.0.1

  # This is introviews animation
  intro_views_flutter: ^2.8.2

  # This is easy share
  share: ^2.0.4

  # This is cache manager
  flutter_cache_manager: ^3.3.0

  # This is path provider
  path_provider: ^2.0.8

  #This is permisson uses
  permission_handler: ^8.3.0

  #FLutter spinKit use plugin
  flutter_spinkit: ^5.1.0

  #This is animated list view use
  flutter_staggered_animations: ^0.1.2
  
  #This is animation floating action button
  fab_circular_menu: ^1.0.1

  #This is save shared prefences
  shared_preferences: ^2.0.11

  #This is icons social icons//
  flutter_awesome_buttons: ^1.1.0

  #Tsis is provider use
  provider: ^6.0.2

  #This is pagination use
  preload_page_view: ^0.1.4

  #This is a local_notifications
  flutter_local_notifications: ^9.1.5

  #Batery Levele data
  battery: ^2.0.3

  #This is line pull to all refresh data
  liquid_pull_to_refresh: ^3.0.0

  #This is line firebase_messaging: ^7.0.3
  # firebase_messaging: ^11.2.4

  firebase_core: ^1.10.6

  cloud_firestore:

  #This is line viedo player 
  video_player: ^2.2.7

  #This is line device_info: ^1.0.0
  device_info: ^2.0.3

  #This is line flutter_carousel_slider: ^1.0.8
  flutter_carousel_slider: ^1.0.8

#  # #This is line admob_flutter: ^1.0.1
#  admob_flutter:

 #This is line lottie: ^1.0.1
  lottie: ^1.0.1

  #This is line flutter_animated_dialog: ^1.2.0
  flutter_animated_dialog: ^1.2.0

  #This is line anitex: ^1.1.0
  anitex: ^1.1.0

  #This is line animated_search_bar: ^2.0.0
  animated_search_bar: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
 
  colorlizer: ^0.0.4
 
  in_app_update: ^2.0.0
 
  font_awesome_flutter: ^9.1.0
 
  flutter_wallpaper_manager: ^0.0.3
 
  image_downloader: ^0.31.0
 
  octo_image: ^1.0.1
 
  firebase_auth: ^3.3.4
 
  onesignal_flutter: ^3.2.7
 
  flutter_bloc: ^8.0.1
 
  equatable: ^2.0.3
 
  logger: ^1.1.0
 
  just_audio: ^0.9.19
 
  in_app_purchase: ^2.0.1
 
  circular_countdown_timer: ^0.2.0

  purchases_flutter: ^3.9.5

  supercharged_dart: ^2.1.1

  supercharged: ^2.1.1

  get: ^4.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - car.jpg
    - forset.jpg
    - night.jpg
    - abstract.jpg
    - boy.jpg
    - darwlogo.png
    - load.gif
    - terms.png
    - proicon.png
    - privacy.png
    - qr_code.png
    - background.png
    - Illustration.png
    - vector_image.png
    - relenewvideo.mp4
    - gif.json
    - snow_json.json
    - circle_loading_lottie.json
    - premimumlottie.json
    - lang/az.json
    - lang/de.json
    - lang/en.json
    - lang/ru.json
    - lang/tr.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-SemiBold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
